USE [FirstWordsAnalyzer]
GO

/****** Object: Table [dbo].[Cognates] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic table backup
-- Generated by Claude Code automation

CREATE TABLE [dbo].[Cognates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BasicWordId] [int] NOT NULL,
	[DerivedWordId] [int] NOT NULL,
	[WordPart] [nvarchar](16) NOT NULL,
	[WrongAssociation] [bit] NULL,
 CONSTRAINT [PK_Cognates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Cognates] WITH CHECK ADD CONSTRAINT [FK_Cognates_Words] FOREIGN KEY([BasicWordId])
REFERENCES [dbo].[Words] ([Id])
GO

ALTER TABLE [dbo].[Cognates] CHECK CONSTRAINT [FK_Cognates_Words]
GO

ALTER TABLE [dbo].[Cognates] WITH CHECK ADD CONSTRAINT [FK_Cognates_Words1] FOREIGN KEY([DerivedWordId])
REFERENCES [dbo].[Words] ([Id])
GO

ALTER TABLE [dbo].[Cognates] CHECK CONSTRAINT [FK_Cognates_Words1]
GO