USE [FirstWordsAnalyzer]
GO

/****** Object: Table [dbo].[SentenceWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic table backup
-- Generated by Claude Code automation

CREATE TABLE [dbo].[SentenceWords](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SentenceId] [int] NOT NULL,
	[WordId] [int] NOT NULL,
 CONSTRAINT [PK_SentenceWords] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SentenceWords] WITH CHECK ADD CONSTRAINT [FK_SentenceWords_Sentences] FOREIGN KEY([SentenceId])
REFERENCES [dbo].[Sentences] ([Id])
GO

ALTER TABLE [dbo].[SentenceWords] CHECK CONSTRAINT [FK_SentenceWords_Sentences]
GO

ALTER TABLE [dbo].[SentenceWords] WITH CHECK ADD CONSTRAINT [FK_SentenceWords_Words] FOREIGN KEY([WordId])
REFERENCES [dbo].[Words] ([Id])
GO

ALTER TABLE [dbo].[SentenceWords] CHECK CONSTRAINT [FK_SentenceWords_Words]
GO