USE [FirstWordsAnalyzer]
GO

/****** Object: Table [dbo].[WordsParts] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic table backup
-- Generated by Claude Code automation

CREATE TABLE [dbo].[WordsParts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[WordId] [int] NOT NULL,
	[WordPart] [nvarchar](16) NOT NULL,
 CONSTRAINT [PK_WordsParts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WordsParts] WITH CHECK ADD CONSTRAINT [FK_WordsParts_Words] FOREIGN KEY([WordId])
REFERENCES [dbo].[Words] ([Id])
GO

ALTER TABLE [dbo].[WordsParts] CHECK CONSTRAINT [FK_WordsParts_Words]
GO