USE [FirstWordsAnalyzer]
GO

/****** Object: Table [dbo].[Words] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic table backup
-- Generated by Claude Code automation

CREATE TABLE [dbo].[Words](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [nvarchar](16) NOT NULL,
	[FirstTranslationVariant] [nvarchar](50) NULL,
	[SecondTranslationVariant] [nvarchar](50) NULL,
	[ThirdTranslationVariant] [nvarchar](50) NULL,
	[NoSense] [bit] NOT NULL,
	[NotBasic] [bit] NOT NULL,
 CONSTRAINT [PK_Words] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO