USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[GetChainOfDerivedWordsWithContext] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic stored procedure backup
-- Generated by Claude Code automation via sp_helptext

CREATE PROC [dbo].[GetChainOfDerivedWordsWithContext]
 @basicWordId AS INT
 
AS
BEGIN
SET NOCOUNT ON;  

WITH CognatesCTE AS
(SELECT [BasicWordId] AS WordId
	   ,[BasicWordId]
	   ,[DerivedWordId]
	   ,0 AS distance
	   ,Id
  FROM [FirstWordsAnalyzer].[dbo].ActualCognates AS UDW
  Where [BasicWordId] = @basicWordId
  
  UNION ALL 

  Select B.WordId
	    ,D.BasicWordId
	    ,D.DerivedWordId
	    ,B.distance + 1
		,D.Id
  FROM CognatesCTE AS B 
  Join [FirstWordsAnalyzer].[dbo].ActualCognates AS D
  On B.DerivedWordId = D.BasicWordId)

  Select Min(CCTE.Id) AS Id
		,Min(CCTE.BasicWordId) AS BasicWordId
		,CCTE.DerivedWordId
		,Min(CCTE.Distance) AS Distance
		,Min(WP.Quantity) As Quantity
		,WWC.WordText
		,WWC.FirstTranslationVariant
		,WWC.SentenceId
		,WWC.SentenceText
  From CognatesCTE AS CCTE
  Join [dbo].[WordsPopularity] AS WP
  ON CCTE.DerivedWordId = WP.WordId
  Join [dbo].[WordsWithContext] AS WWC
  On CCTE.DerivedWordId = WWC.WordId
  Group By CCTE.DerivedWordId, WWC.WordText, WWC.FirstTranslationVariant, WWC.SentenceId, WWC.SentenceText   
  Order By Min(WP.Quantity) DESC

  END

GO
