USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[GetSentencesWithWord] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic stored procedure backup
-- Generated by Claude Code automation via sp_helptext

CREATE PROC [dbo].[GetSentencesWithWord]
 @wordId AS INT
 
AS
BEGIN
SET NOCOUNT ON;  

SELECT TOP (20) SentenceId AS Id, BookId, Text, Length
  FROM [FirstWordsAnalyzer].[dbo].[SentenceWords] AS SW
  Join [dbo].[Sentences] AS S
  On SW.SentenceId = S.Id
  Where SW.WordId = @wordId
  Order By Length

  END

GO
