USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[BaseWordsPopularity] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This view will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[BaseWordsPopularity]
AS 
With CTE AS
(SELECT C.[DerivedWordId] AS DerivedWordId
	  ,C.[BasicWordId] AS BasicWordId
	  ,C1.BasicWordId AS BasicWordId1
	  ,C2.BasicWordId AS BasicWordId2
	  ,C3.BasicWordId AS BasicWordId3
  FROM [FirstWordsAnalyzer].[dbo].[Cognates] AS C
  Left Join [FirstWordsAnalyzer].[dbo].[Cognates] AS C1
  On C.BasicWordId = C1.DerivedWordId
  Left Join [FirstWordsAnalyzer].[dbo].[Cognates] AS C2
  On C1.BasicWordId = C2.DerivedWordId
  Left Join [FirstWordsAnalyzer].[dbo].[Cognates] AS C3
  On C2.BasicWordId = C3.DerivedWordId
),

CTE1 AS
(SELECT 
		--CTE.DerivedWordId, DW.Text, WP.quantity AS WPquantity,
		--CTE.BasicWordId,   BW.Text, WP.quantity + WP1.quantity AS WP1quantity,
		--CTE.BasicWordId1,  BW1.Text, WP.quantity + WP1.quantity + WP2.quantity AS WP2quantity,
		--CTE.BasicWordId2,  BW2.Text, WP.quantity + WP1.quantity + WP2.quantity + WP3.quantity AS WP3quantity,
        --CTE.BasicWordId3, BW3.Text, WP.quantity + WP1.quantity + WP2.quantity + WP3.quantity + WP4.quantity AS WP4quantity,
		COALESCE(BasicWordId3, BasicWordId2, BasicWordId1, BasicWordId, DerivedWordId) AS TotalBasicWordId, 
		COALESCE(WP4.quantity, 0) +  COALESCE(WP3.quantity, 0) + COALESCE(WP2.quantity, 0) + COALESCE(WP1.quantity, 0) + COALESCE(WP.quantity, 0) AS TotalWPquantity
From CTE Join [dbo].[Words] AS DW
On CTE.DerivedWordId = DW.Id
Left Join [dbo].[Words] AS BW
On CTE.BasicWordId = BW.Id
Left Join [dbo].[Words] AS BW1
On CTE.BasicWordId1 = BW1.Id
Left Join [dbo].[Words] AS BW2
On CTE.BasicWordId2 = BW2.Id
Left Join [dbo].[Words] AS BW3
On CTE.BasicWordId3 = BW3.Id
  Left Join WordsPopularity AS WP
  On CTE.DerivedWordId = WP.WordId
  Left Join WordsPopularity AS WP1
  On CTE.BasicWordId = WP1.WordId
  Left Join WordsPopularity AS WP2
  On CTE.BasicWordId1 = WP2.WordId
  Left Join WordsPopularity AS WP3
  On CTE.BasicWordId2 = WP3.WordId
  Left Join WordsPopularity AS WP4
  On CTE.BasicWordId3 = WP4.WordId
Where CTE.DerivedWordId Not In(Select CTE.BasicWordId From CTE))

Select TotalBasicWordId AS BasicWordId, Max(TotalWPquantity) AS Quantity
From CTE1
Group By TotalBasicWordId

GO