USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[ExistingWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This view will be deleted as part of database cleanup
-- Generated by Claude Code automation

Create View ExistingWords
AS
Select *
From [dbo].[Words]
Where NoSense = 0

GO