USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[GetChainOfDerivedWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This stored procedure will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

CREATE PROC GetChainOfDerivedWords
 @basicWordId AS INT
 
AS
BEGIN
SET NOCOUNT ON;  

WITH CognatesCTE AS
(SELECT [BasicWordId] AS WordId
	   ,[BasicWordId]
	   ,[DerivedWordId]
	   ,0 AS distance
  FROM [FirstWordsAnalyzer].[dbo].[UniqueDerivedWords] AS UDW
  Where BasicWordId not in(Select DerivedWordId From [FirstWordsAnalyzer].[dbo].[Cognates])
  AND [BasicWordId] = @basicWordId 
  
  UNION ALL 

  Select B.WordId
	    ,D.BasicWordId
	    ,D.DerivedWordId
	    ,B.distance + 1
  FROM CognatesCTE AS B 
  Join [FirstWordsAnalyzer].[dbo].[UniqueDerivedWords] AS D
  On B.DerivedWordId = D.BasicWordId)

  Select CCTE.BasicWordId, CCTE.DerivedWordId, CCTE.distance, WP.Quantity
  From CognatesCTE AS CCTE
  Join [dbo].[WordsPopularity] AS WP
  ON CCTE.DerivedWordId = WP.WordId

  END

GO