USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[GetWordsPopularity] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This stored procedure will be deleted as part of database cleanup
-- Generated by Claude Code automation

CREATE PROC [dbo].[GetWordsPopularity]
AS
BEGIN
 SET NOCOUNT ON;
	SELECT WordId, Count(*) AS Quantity
	Into #T1
	FROM [FirstWordsAnalyzer].[dbo].[SentenceWords]
	Group By WordId  

	SELECT WordId, Quantity
	FROM #T1;  
 RETURN;
END

GO