USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[MyProcedure] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This stored procedure will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

CREATE Procedure [dbo].[MyProcedure]
@param1 as numeric(15,2),
@param2 as int,
@param3 as nvarchar(30),
@param4 as bit,
@param5 as nchar,
@param6 as datetime

AS

Begin
Select  Cast(@param2 as numeric(15,2)) / @param1 AS FirsColumn
	   ,TRY_CONVERT(nvarchar, @param6) AS SecondColumn
	   ,TRY_PARSE(@param5 as int) AS ThirdColumn
	   ,TRY_CONVERT(int, @param4) AS ForthColumn	
END

GO