USE [FirstWordsAnalyzer]
GO

/****** Object: StoredProcedure [dbo].[SetWrongAssociation] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This stored procedure will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE SetWrongAssociation 
	-- Add the parameters for the stored procedure here
	@basicWordId int,
	@derivedWordId int
	AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
    -- Insert statements for procedure here

UPDATE [FirstWordsAnalyzer].[dbo].[Cognates]
 SET [WrongAssociation] = 1
 WHERE [BasicWordId] = @basicWordId AND [DerivedWordId] = @derivedWordId

END

GO