USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[ActualCognates] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[ActualCognates]
AS
Select C.[BasicWordId], C.[DerivedWordId], C.[WordPart], C.Id
From [dbo].[Cognates] AS C
Join [dbo].[Words] AS BW
On C.BasicWordId = BW.Id
AND BW.NoSense = 0
AND BW.NotBasic = 0
Join [dbo].[Words] AS DW
On C.DerivedWordId = DW.Id
AND DW.NoSense = 0
Where [WrongAssociation] = 0

GO