USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[ChainsOfDerivedWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This view will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[ChainsOfDerivedWords] AS

WITH CognatesCTE AS
(SELECT [BasicWordId] AS WordId
	   ,[BasicWordId]
	   ,[DerivedWordId]
	   ,0 AS distance
	   ,Id
  FROM [FirstWordsAnalyzer].[dbo].[ActualCognates] AS UDW
  Where BasicWordId not in(Select DerivedWordId From [FirstWordsAnalyzer].[dbo].[ActualCognates])
  
  UNION ALL 

  Select B.WordId
	    ,D.BasicWordId
	    ,D.DerivedWordId
	    ,B.distance + 1
		,D.Id
  FROM CognatesCTE AS B 
  Join [FirstWordsAnalyzer].[dbo].[ActualCognates] AS D
  On B.DerivedWordId = D.BasicWordId)

  Select CCTE.Id, CCTE.WordId, CCTE.BasicWordId, CCTE.DerivedWordId, CCTE.distance, WP.Quantity
  From CognatesCTE AS CCTE
  Join [dbo].[WordsPopularity] AS WP
  ON CCTE.DerivedWordId = WP.WordId

GO