USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[DerivedWordsPopularityForBaseWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[DerivedWordsPopularityForBaseWords]

AS

WITH CognatesCTE AS
(SELECT [BasicWordId] AS WordId
	   ,[BasicWordId]
	   ,[DerivedWordId]
	   ,0 AS distance
  FROM [FirstWordsAnalyzer].[dbo].[UniqueDerivedWords]
  Where BasicWordId not in(Select DerivedWordId From [FirstWordsAnalyzer].[dbo].[ActualCognates])
  
  UNION ALL 

  Select B.WordId
	    ,D.BasicWordId
	    ,D.DerivedWordId
	    ,B.distance + 1
  FROM CognatesCTE AS B 
  Join [FirstWordsAnalyzer].[dbo].[UniqueDerivedWords] AS D
  On B.DerivedWordId = D.BasicWordId)

  Select CCTE.WordId, Sum(WP.Quantity) AS Quantity
  From CognatesCTE AS CCTE
  Join [dbo].[WordsPopularity] AS WP
  ON CCTE.DerivedWordId = WP.WordId
  Group By CCTE.WordId

GO
