USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[ExistingWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup  
-- Generated by Claude Code automation

Create View ExistingWords
AS
Select *
From [dbo].[Words]
Where NoSense = 0

GO
