USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[UniqueDerivedWords] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- This view will be deleted as part of database cleanup
-- Generated by Claude Code automation via sp_helptext

CREATE VIEW [dbo].[UniqueDerivedWords]  
AS

With CTEUnicBasicWords AS
(SELECT DerivedWordId
       ,MAX(LEN([WordPart])) AS Length
  FROM [FirstWordsAnalyzer].[dbo].[ActualCognates]
  Group By [DerivedWordId])

Select C.DerivedWordId, C.BasicWordId, C.WordPart, C.Id
  From CTEUnicBasicWords Left Join [FirstWordsAnalyzer].[dbo].[ActualCognates] AS C
  On CTEUnicBasicWords.DerivedWordId = C.DerivedWordId
  AND CTEUnicBasicWords.Length = LEN(C.WordPart)

GO