USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[WordsPopularityWithCognates] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[WordsPopularityWithCognates]

AS

SELECT WP.[WordId]
	  ,W.Text
	  ,W.FirstTranslationVariant
	  ,W.SecondTranslationVariant
	  ,W.ThirdTranslationVariant
      ,COALESCE(BWP.[Quantity], 0) + WP.[Quantity] AS Quantity
	  ,COALESCE(BWP.[Quantity], 0) AS Differance
  FROM [WordsPopularity] AS WP
  Left Join [DerivedWordsPopularityForBaseWords] AS BWP
  On WP.[WordId] = BWP.[WordId]
  Left Join [dbo].[Words] AS W
  On WP.Wordid = W.Id
  Where WP.WordId not in(Select DerivedWordId From [FirstWordsAnalyzer].[dbo].[ActualCognates])
  And COALESCE(BWP.[Quantity], 0) > 0

GO