USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[WordsPopularity] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup
-- Generated by Claude Code automation via sp_helptext

CREATE View [dbo].[WordsPopularity]
AS
SELECT WordId, Count(*) AS Quantity
FROM [FirstWordsAnalyzer].[dbo].[SentenceWords]
Group By WordId

GO