USE [FirstWordsAnalyzer]
GO

/****** Object: View [dbo].[WordsWithContext] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Backup created on: 2025-07-19
-- Main logic view backup
-- Generated by Claude Code automation via sp_helptext

Create View WordsWithContext

AS

With CTEMinLength AS
(SELECT [WordId]
	  ,Min(S.Length) Length
FROM [dbo].[SentenceWords] AS SW
Left Join [dbo].[Sentences] AS S
ON SW.SentenceId = S.Id
Group By [WordId]),

CTEWithSentences AS
(
Select SW.WordId, Min(SentenceId) AS SentenceId
From CTEMinLength
Join [dbo].[SentenceWords] AS SW
ON CTEMinLength.WordId = SW.WordId
Join [dbo].[Sentences] AS S
On SW.SentenceId = S.Id
AND CTEMinLength.Length = S.Length
Group By SW.WordId)

Select W.Id AS WordId, W.Text AS WordText, W.FirstTranslationVariant, S.Id AS SentenceId, S.Text AS SentenceText, S.Length
From CTEWithSentences AS CTE
Join [dbo].[Words] AS W
On CTE.WordId = W.Id
Join [dbo].[Sentences] AS S
On CTE.SentenceId = S.Id

GO
