//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWordsAnalyzer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FirstWordsAnalyzerEntities : DbContext
    {
        public FirstWordsAnalyzerEntities()
            : base("name=FirstWordsAnalyzerEntities")
        {
            this.Database.CommandTimeout = 60;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Sentence> Sentences { get; set; }
        public virtual DbSet<SentenceWord> SentenceWords { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<Cognate> Cognates { get; set; }
        public virtual DbSet<WordsPopularityWithCognates2> WordsPopularityWithCognates2 { get; set; }
        public virtual DbSet<PotentialCognate> PotentialCognates { get; set; }
    
    
        public virtual ObjectResult<GetChainOfDerivedWordsWithContext_Result> GetChainOfDerivedWordsWithContext(Nullable<int> basicWordId)
        {
            var basicWordIdParameter = basicWordId.HasValue ?
                new ObjectParameter("basicWordId", basicWordId) :
                new ObjectParameter("basicWordId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChainOfDerivedWordsWithContext_Result>("GetChainOfDerivedWordsWithContext", basicWordIdParameter);
        }
    }
}
