//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWordsAnalyzer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirstWordsAnalyzerEntities : DbContext
    {
        public FirstWordsAnalyzerEntities()
            : base("name=FirstWordsAnalyzerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Sentence> Sentences { get; set; }
        public virtual DbSet<SentenceWord> SentenceWords { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<Cognate> Cognates { get; set; }
    }
}
