//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWordsAnalyzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentenceWord
    {
        public int SentenceId { get; set; }
        public int WordId { get; set; }
        public decimal Number { get; set; }
    
        public virtual Sentence Sentence { get; set; }
        public virtual Word Word { get; set; }
    }
}
