//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWordsAnalyzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsPopularityWithCognates2
    {
        public int WordId { get; set; }
        public string Text { get; set; }
        public string FirstTranslationVariant { get; set; }
        public string SecondTranslationVariant { get; set; }
        public string ThirdTranslationVariant { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Differance { get; set; }
    }
}
